# Master schema for column datatypes in dataframes
# Used for validation and type conversion

pert_name: string
pert2_name: string
pert_id: string
pert2_id: string
pert_dose: float
pert2_dose: float
pert_dose_unit: string
pert2_dose_unit: string
pert_type: string
lua: string
depmap_id: string
cell_set: string
pool_id: string
day: integer
pcr_well: string
pcr_plate: string
pert_plate: string
bio_rep: integer
tech_rep: integer
replicate_plate: string
pert_vehicle: string
is_combination: boolean
cb_ladder: string
cb_name: string
cb_log2_dose: float
growth_pattern: string
cb_intercept: float
log2_normalized_n: float
n: integer
mad_log2_cb_frac: float
num_reps: integer
log2_pseudovalue: float
l2fc: float
contrrol_median_normalized_n: float
mean_normalized_n: float
x_project_id: string
index_1: string
index_2: string
flowcell_names: string
flowcell_lanes: string
expected_read: boolean
median_l2fc: float
median_l2fc_uncorrected: float
project_code: string
median_log_normalized_ctl_vehicle: float
median_log_normalized_trt_poscon: float
mad_log_normalized_ctl_vehicle: float
mad_log_normalized_trt_poscon: float
median_raw_ctl_vehicle: float
median_raw_trt_poscon: float
mad_raw_ctl_vehicle: float
mad_raw_trt_poscon: float
n_replicates_ctl_vehicle: integer
n_replicates_trt_poscon: integer
false_sensitivity_probability_50: float
false_sensitivity_probability_25: float
error_rate: float
lfc_trt_poscon: float
lfc_raw_trt_poscon: float
viability_trt_poscon: float
total_reads: integer
fraction_of_reads: float
med_num_trt_bio_reps: integer
qc_pass: boolean
qc_pass_pert_plate: boolean
n_passing_med_num_trt_reps: integer
n_expected_ctl_vehicle: integer
n_expected_trt_poscon: integer
fraction_expected_poscon: float
fraction_expected_negcon: float
qc_flag: string
n_total_reads: integer
n_expected_reads: integer
n_cb_reads: integer
median_cb_reads: float
fraction_expected_reads: float
n_lines_recovered: integer
n_expected_lines: integer
fraction_cl_recovered: float
cb_cl_ratio_well: float
fraction_cb_reads: float
cb_cl_ratio_plate: float
skew: float
cb_mae: float
cb_r2: float
cb_spearman: float
n_cell_lines: integer
n_outliers: integer
fraction_outliers: float