install.packages("argparse")
install.packages("magrittr")
install.packages("tidyverse")
install.packages("BiocManager")
install.packages("scam")
install.packages("readr")
install.packages("stringr")
install.packages("dplyr")
install.packages("tidyr")
install.packages("sets")
install.packages("devtools")
library(devtools)
devtools::install_github("broadinstitute/cdsr_models", dependencies=TRUE)
devtools::install_github("broadinstitute/cdsr_biomarker", dependencies=TRUE)
BiocManager::install("cmapR")