options(repos = c(
  "https://iwww.broadinstitute.org/~datasci/R-packages",
  "https://cran.rstudio.com/"))
install.packages('taigr')

options(repos=structure(c(CRAN="http://cran.r-project.org")))

install.packages("tidyverse")
install.packages("hdf5r")
install.packages("reshape2")
install.packages("readr")
install.packages("magrittr")
install.packages("dr4pl")
install.packages("data.table")
install.packages("scam")
install.packages("argparse")
install.packages("splitstackshape")
install.packages("BiocManager")
BiocManager::install()
BiocManager::install("sva")
BiocManager::install("limma", ask = FALSE)
BiocManager::install('apeglm')
BiocManager::install('ShortRead')
install.packages("PRROC")
install.packages("gmodels")
install.packages("R.utils")
install.packages("devtools")
devtools::install_github("broadinstitute/cdsr_models", dependencies=TRUE, force=TRUE)
devtools::install_github("broadinstitute/cdsr_biomarker")
devtools::install_github('https://github.com/cmap/sushi')
