# Install CRAN packages
install.packages("ranger", dependencies = TRUE)
install.packages("dr4pl", dependencies = TRUE)
install.packages("drc", dependencies = TRUE)
install.packages("argparse", dependencies = TRUE)
install.packages("magrittr", dependencies = TRUE)
install.packages("tidyverse", dependencies = TRUE)
install.packages("BiocManager", dependencies = TRUE)
install.packages("scam", dependencies = TRUE)
install.packages("readr", dependencies = TRUE)
install.packages("stringr", dependencies = TRUE)
install.packages("dplyr", dependencies = TRUE)
install.packages("tidyr", dependencies = TRUE)
install.packages("sets", dependencies = TRUE)
install.packages("ggpubr", dependencies = TRUE)
install.packages("ggpmisc", dependencies = TRUE)
install.packages("stringdist", dependencies = TRUE)
install.packages("devtools", dependencies = TRUE)
install.packages("reshape2", dependencies = TRUE)
install.packages("R.utils", dependencies = TRUE)
install.packages("PRROC", dependencies = TRUE)
install.packages("aws.s3", dependencies = TRUE)
install.packages("aws.signature", dependencies = TRUE)
install.packages("here", dependencies = TRUE)
devtools::install_github("https://github.com/broadinstitute/taigr")

# Install other necessary Bioconductor packages explicitly
BiocManager::install("S4Vectors")
BiocManager::install("IRanges")
BiocManager::install("GenomeInfoDb")
BiocManager::install("XVector")
BiocManager::install("Biostrings")
BiocManager::install("KEGGREST")
BiocManager::install("AnnotationDbi")
BiocManager::install("GO.db")
BiocManager::install("WGCNA")
BiocManager::install("rhdf5")
